use std::env;
use std::path::PathBuf;

// generated by `sqlx migrate build-script`
fn main() -> Result<(), Box<dyn std::error::Error>> {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    tonic_build::configure()
        .file_descriptor_set_path(out_dir.join("echo_descriptor.bin"))
        .compile(&["proto/echo.proto"], &["proto"])?;

    tonic_build::compile_protos("proto/echo.proto")?;
    tonic_build::compile_protos("proto/song.proto")?;
    
    Ok(())
}