apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service
  namespace: song-service
  labels:
    app: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service
          image: nurnechushtan/song_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      