apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: song-service-custom-hpa
  namespace: song-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: song-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: grpc_requests_per_second
        target:
          type: AverageValue
          averageValue: 20000m