apiVersion: v1
kind: Service
metadata:
  name: song-service-headless
  labels:
    app: song-service
  namespace: song-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: song-service
  ports:
    - protocol: TCP
      name: grpc
      port: 50051
      targetPort: 50051
