on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

  update_deployment:
    name: Update deployment file in GitOps repository
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Clone the repository
        run: git clone https://x-access-token:${{ secrets.PAT }}@github.com/nur1210/soundseeker-k8s.git

      - name: Update image tag in deployment file
        run: |
          cd soundseeker-k8s
          sed -i 's|${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:.*|${{ secrets.NAMESPACE }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}|g' ${{ secrets.DEPLOYMENT_FILE_PATH }}

      - name: Commit and push changes
        run: |
          cd soundseeker-k8s
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "nur1210"
          git add .
          git commit -m "Update image tag"
          git push